# Invoked by mxlgw_embed_file(): writes a header with the input bytes as a char array.
file(READ "${INPUT}" _hex HEX)
string(LENGTH "${_hex}" _len)
math(EXPR _bytes "${_len} / 2")
string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," _body "${_hex}")
string(REGEX REPLACE "(0x[0-9a-f][0-9a-f],){32}" "\\0\n    " _body "${_body}")
get_filename_component(_dir "${OUTPUT}" DIRECTORY)
file(MAKE_DIRECTORY "${_dir}")
file(WRITE "${OUTPUT}.tmp"
"// Generated by cmake/EmbedFileScript.cmake from ${INPUT}. Do not edit.\n"
"#pragma once\n"
"#include <cstddef>\n"
"#include <string_view>\n"
"namespace mxlgw::embedded {\n"
"inline constexpr unsigned char ${VAR}Bytes[] = {\n    ${_body}0x00};\n"
"inline constexpr std::size_t ${VAR}Size = ${_bytes};\n"
"inline std::string_view ${VAR}() { return {reinterpret_cast<char const*>(${VAR}Bytes), ${VAR}Size}; }\n"
"}\n")
file(COPY_FILE "${OUTPUT}.tmp" "${OUTPUT}" ONLY_IF_DIFFERENT)
file(REMOVE "${OUTPUT}.tmp")
