# Optional integrations. AUTO enables a component when its dependency is found.

function(_mxlgw_resolve name found)
    if(MXLGW_WITH_${name} STREQUAL "ON" AND NOT ${found})
        message(FATAL_ERROR "MXLGW_WITH_${name}=ON but the dependency was not found")
    endif()
    if(MXLGW_WITH_${name} STREQUAL "OFF")
        set(MXLGW_HAVE_${name} OFF PARENT_SCOPE)
    elseif(${found})
        set(MXLGW_HAVE_${name} ON PARENT_SCOPE)
    else()
        set(MXLGW_HAVE_${name} OFF PARENT_SCOPE)
    endif()
endfunction()

set(_mxl_found OFF)
if(NOT MXLGW_WITH_MXL STREQUAL "OFF")
    find_package(mxl CONFIG QUIET)
    if(mxl_FOUND)
        set(_mxl_found ON)
    endif()
endif()
_mxlgw_resolve(MXL _mxl_found)

set(_mtl_found OFF)
if(NOT MXLGW_WITH_MTL STREQUAL "OFF")
    find_package(PkgConfig QUIET)
    if(PkgConfig_FOUND)
        pkg_check_modules(MTL QUIET IMPORTED_TARGET mtl)
        # DPDK headers/libs for the read-only ethdev queries (MAC, link) of ports MTL owns (§4.5).
        pkg_check_modules(DPDK QUIET libdpdk)
        if(MTL_FOUND AND DPDK_FOUND)
            set(_mtl_found ON)
        endif()
    endif()
endif()
_mxlgw_resolve(MTL _mtl_found)

set(_nmos_found OFF)
if(NOT MXLGW_WITH_NMOS STREQUAL "OFF")
    # nmos-cpp's package config links websocketpp::websocketpp without finding it.
    find_package(websocketpp CONFIG QUIET)
    find_package(nmos-cpp CONFIG QUIET)
    if(nmos-cpp_FOUND)
        set(_nmos_found ON)
    endif()
endif()
_mxlgw_resolve(NMOS _nmos_found)
